# Generated by Django 3.0.3 on 2020-03-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhmoi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhmos',
            name='address',
            field=models.CharField(blank=True, default='-', max_length=100, verbose_name='Διεύθυνση'),
        ),
        migrations.AddField(
            model_name='dhmos',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Κατάσταση'),
        ),
    ]
