# Generated by Django 3.0.3 on 2020-03-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhmoi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhmos',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Κατάσταση'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Κατάσταση'),
        ),
    ]
