# Generated by Django 3.0.3 on 2020-08-14 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhmoi', '0002_auto_20200814_0907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
