# Generated by Django 3.0.3 on 2020-08-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhmoi', '0003_delete_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tameiaki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200, verbose_name='Επωνυμία')),
                ('business', models.CharField(max_length=200, verbose_name='Επιχείρηση')),
                ('afm', models.CharField(max_length=200, verbose_name='Α.Φ.Μ')),
                ('address', models.CharField(max_length=200, verbose_name='Διεύθυνση')),
                ('phone', models.CharField(max_length=50, verbose_name='Τηλέφωνο')),
                ('cash_model', models.CharField(blank=True, choices=[('Datecs CTR 220', 'Datecs CTR 220'), ('Datecs WP 500', 'Datecs WP 500'), ('Datecs Pocket', 'Datecs Pocket')], max_length=150, null=True, verbose_name='Μοντέλο Ταμ.')),
                ('old_os_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Τρέχον έκδοση λογισμικού')),
                ('new_os_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Νέα έκδοση λογισμικού')),
                ('cash_register_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Αρ. Μητρώου Ταμειακής')),
                ('submission_date', models.DateField(auto_now_add=True, verbose_name='Ημερομηνία Υποβολής TAXIS')),
                ('status', models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], max_length=150, null=True, verbose_name='Κατάσταση')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ταμειακές',
                'verbose_name_plural': 'Ταμειακές',
            },
        ),
    ]
