# Generated by Django 3.0.3 on 2020-03-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhmoi', '0003_dhmos_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Κατάσταση'),
        ),
    ]
