# Generated by Django 3.0.3 on 2020-03-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhmoi', '0003_dhmos_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhmos',
            name='city',
            field=models.CharField(blank=True, default='-', max_length=100, verbose_name='Πόλη'),
        ),
    ]
