# Generated by Django 3.0.3 on 2020-06-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhmoi', '0003_auto_20200603_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ergasies',
            name='symbasi',
            field=models.ManyToManyField(blank=True, to='dhmoi.Symbasi', verbose_name='Σύμβαση'),
        ),
    ]
