# Generated by Django 3.0.3 on 2020-06-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhmoi', '0004_auto_20200603_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ergasies',
            name='symbasi',
        ),
        migrations.DeleteModel(
            name='Symbasi',
        ),
    ]
