# Generated by Django 3.0.2 on 2020-03-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhmoi', '0004_employee_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='tmhma',
            field=models.CharField(blank=True, choices=[('1', 'Οικονομική'), ('2', 'Τεχνική'), ('3', 'Διοικητική'), ('4', 'Γραφείο Προσωπικού'), ('5', 'Μισθοδοσία'), ('6', 'Γραφείο Δημάρχου'), ('7', 'Τμήμα Πληροφορικής'), ('8', 'Ληξιαρχείο'), ('9', 'Αντιδήμαρχος'), ('10', 'Γραφείο Κίνησης')], max_length=100, verbose_name='Υπηρεσία'),
        ),
        migrations.AlterField(
            model_name='ergasies',
            name='app',
            field=models.CharField(blank=True, choices=[('ΤΑΠ', 'ΤΑΠ'), ('Μισθοδοσία', 'Μισθοδοσία'), ('Διαχείριση Προσωπικού', 'Διαχείριση Προσωπικού'), ('Λογιστική', 'Λογιστική'), ('Μητρώο Πολιτών', 'Μητρώο Πολιτών'), ('Ύδρευση', 'Ύδρευση'), ('Αποφάσεις', 'Αποφάσεις'), ('Πρωτόκολλο', 'Πρωτόκολλο'), ('Γραφείο Κίνησης', 'Γραφείο Κίνησης'), ('Διαύγεια', 'Διαύγεια'), ('Έσοδα', 'Έσοδα'), ('Κοιμητήρια', 'Κοιμητήρια'), ('ΚΟΚ', 'ΚΟΚ'), ('Δημοτικός φόρος', 'Δημοτικός φόρος'), ('Site', 'Site'), ('Πρακτικό', 'Πρακτικό'), ('Hardware', 'Hardware')], max_length=100, verbose_name='Εφαρμογή'),
        ),
    ]
