# Generated by Django 3.0.3 on 2020-03-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhmoi', '0005_ergasies_is_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ergasies',
            name='is_visible',
        ),
    ]
