# Generated by Django 3.0.7 on 2020-09-11 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dhmoi', '0005_auto_20200902_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='aithmata',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Τηλ. επικοινωνίας'),
        ),
        migrations.AlterField(
            model_name='aithmata',
            name='assign',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Χρέωση - ACS'),
        ),
    ]
