# Generated by Django 3.0.3 on 2020-03-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhmoi', '0006_remove_ergasies_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='ergasies',
            name='warning',
            field=models.CharField(choices=[('!', '!')], default='-', max_length=20, verbose_name='!'),
        ),
    ]
