# Generated by Django 3.0.3 on 2020-03-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhmoi', '0007_ergasies_warning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ergasies',
            name='warning',
            field=models.CharField(choices=[('!', '!'), ('-', '-')], default='-', max_length=20, verbose_name='!'),
        ),
    ]
