# Generated by Django 3.0.7 on 2020-11-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhmoi', '0007_auto_20200929_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=250, verbose_name='Version')),
                ('description', models.CharField(max_length=300, verbose_name='Περιγραφή')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Αναβαθμίσεις εφαργμογής',
                'verbose_name_plural': 'Αναβαθμίσεις εφαρμογής',
                'db_table': 'app_update',
            },
        ),
    ]
