# Generated by Django 3.0.7 on 2020-11-07 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhmoi', '0008_update'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Update',
        ),
    ]
