# Generated by Django 3.0.3 on 2020-03-27 16:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dhmoi', '0009_remove_ergasies_warning'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreas', models.CharField(choices=[('OTS', 'OTS'), ('Interlei', 'Interlei')], default='OTS', max_length=100, verbose_name='Φορέας')),
                ('importdate', models.DateField(default=datetime.date.today, verbose_name='Καταχώρηση')),
                ('training_type', models.CharField(choices=[('Εκπαίδευση', 'Εκπαίδευση')], default='Εκπαίδευση', max_length=100, verbose_name='Εκαπίδευση')),
                ('app', models.CharField(blank=True, choices=[('ΤΑΠ', 'ΤΑΠ'), ('Μισθοδοσία', 'Μισθοδοσία'), ('Διαχείριση Προσωπικού', 'Διαχείριση Προσωπικού'), ('Λογιστική', 'Λογιστική'), ('Μητρώο Πολιτών', 'Μητρώο Πολιτών'), ('Ύδρευση', 'Ύδρευση'), ('Αποφάσεις', 'Αποφάσεις'), ('Πρωτόκολλο', 'Πρωτόκολλο'), ('Γραφείο Κίνησης', 'Γραφείο Κίνησης'), ('Διαύγεια', 'Διαύγεια'), ('Έσοδα', 'Έσοδα'), ('Κοιμητήρια', 'Κοιμητήρια'), ('ΚΟΚ', 'ΚΟΚ'), ('Δημοτικός φόρος', 'Δημοτικός φόρος'), ('Site', 'Site'), ('Πρακτικό', 'Πρακτικό'), ('Hardware', 'Hardware')], max_length=100, verbose_name='Εφαρμογή')),
                ('time', models.FloatField()),
                ('info', models.TextField(blank=True, max_length=500, null=True, verbose_name='Περιγραφή\xa0')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Υπάλληλος')),
            ],
            options={
                'verbose_name': 'Εκπαιδεύσεις',
                'verbose_name_plural': 'Εκπαιδεύσεις',
            },
        ),
    ]
