# Generated by Django 3.0.7 on 2020-12-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhmoi', '0009_delete_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ergasies',
            name='time',
            field=models.FloatField(verbose_name='Διάρκεια'),
        ),
    ]
