# Generated by Django 3.0.3 on 2020-03-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhmoi', '0010_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='time',
            field=models.FloatField(verbose_name='Διάρκεια'),
        ),
    ]
