# Generated by Django 3.0.7 on 2020-12-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhmoi', '0010_auto_20201217_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ergasies',
            name='time',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Διάρκεια'),
        ),
    ]
