# Generated by Django 3.0.3 on 2020-03-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhmoi', '0011_auto_20200327_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='place',
            field=models.CharField(choices=[('Remote', 'Remote'), ('Γραφεία OTS', 'Γραφεία OTS'), ('Γραφείο ACS', 'Γραφείο ACS')], default='-', max_length=100, verbose_name='Χώρος'),
        ),
    ]
