# Generated by Django 3.0.7 on 2021-01-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhmoi', '0012_auto_20201231_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polisi',
            name='etos',
            field=models.PositiveIntegerField(default=2021, verbose_name='Έτος'),
        ),
    ]
