# Generated by Django 3.0.3 on 2020-03-29 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhmoi', '0013_profile_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_active',
        ),
    ]
