# Generated by Django 3.0.7 on 2020-08-27 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='closed',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
