# Generated by Django 3.0.7 on 2020-08-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='closed',
            field=models.DateField(blank=True, null=True, verbose_name='Ημ. Κλεισίματος'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
