# Generated by Django 3.0.7 on 2020-12-10 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timologisi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prosfora',
            name='date_send',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=' Ημ.Αποστολής'),
            preserve_default=False,
        ),
    ]
