# Generated by Django 3.0.7 on 2020-10-20 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dhmoi', '0007_auto_20200929_0941'),
        ('timologisi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_end', models.DateField(verbose_name=' Ημ.Λήξης')),
                ('contract_sign', models.DateField(verbose_name=' Ημ.Υπογραφ.')),
                ('contract_code', models.CharField(choices=[('HARD00', 'HARD00'), ('SOFT00', 'SOFT00')], max_length=150, verbose_name='Κωδικός Σύμβ.')),
                ('contract_ammount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ποσό Σύμβασης')),
                ('contract_desc', models.TextField(blank=True, null=True, verbose_name='Περιγραφή Σύμβασης')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dhmoi.Employee', verbose_name='Επαφή')),
                ('pelatis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhmoi.Dhmos')),
            ],
            options={
                'verbose_name': 'Σύμβαση',
                'verbose_name_plural': 'Σύμβαση',
                'ordering': ['id'],
            },
        ),
    ]
