# Generated by Django 3.0.3 on 2020-10-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timologisi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prosfora',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
