# Generated by Django 3.0.7 on 2020-10-23 15:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dhmoi', '0007_auto_20200929_0941'),
        ('timologisi', '0002_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(verbose_name=' Ημ.Τιμολόγησης')),
                ('ammount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ποσό')),
                ('bank', models.CharField(choices=[('Τράπεζα Πειραιώς', 'Τράπεζα Πειραιώς'), ('Εθνική Τράπεζα', 'Εθνική Τράπεζα'), ('AlphaBank', 'AlphaBank'), ('EuroBank', 'Eurobank')], max_length=150, verbose_name='Τράπεζα')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Πληρώθηκε')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timologisi.Contract', verbose_name='Κωδ.Συμβ.')),
                ('pelatis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhmoi.Dhmos')),
            ],
        ),
    ]
