# Generated by Django 3.0.7 on 2020-12-14 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timologisi', '0002_prosfora_date_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_code',
            field=models.IntegerField(blank=True, default=0, verbose_name='Κωδ.Τιμ'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_type',
            field=models.CharField(choices=[('Δόσεις', 'Δόσεις'), ('Εφάπαξ', 'Εφάπαξ')], default='------', max_length=150, verbose_name='Τύπος πληρωμής'),
        ),
    ]
