# Generated by Django 3.0.7 on 2020-09-30 20:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dhmoi', '0007_auto_20200929_0941'),
        ('timologisi', '0002_auto_20200929_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosfora',
            name='poso',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ποσό'),
        ),
        migrations.CreateModel(
            name='Symbasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField(default=datetime.date.today, verbose_name='Ημ.Λήξης')),
                ('sign_date', models.DateField(default=datetime.date.today, verbose_name='Ημ.Υπογρ.')),
                ('symbasi', models.CharField(choices=[('REL00', 'REL00'), ('HARD00', 'HARD00')], max_length=100)),
                ('symbasi_description', models.TextField(blank=True, max_length=600, null=True)),
                ('pelatis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhmoi.Dhmos', verbose_name='Πελάτης')),
            ],
        ),
    ]
