# Generated by Django 3.0.7 on 2020-11-07 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timologisi', '0003_auto_20201023_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['id'], 'verbose_name': 'Τιμολόγηση', 'verbose_name_plural': 'Τιμολόγηση'},
        ),
    ]
