# Generated by Django 3.0.7 on 2020-12-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timologisi', '0003_auto_20201214_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosfora',
            name='app',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
