# Generated by Django 3.0.7 on 2020-12-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timologisi', '0004_auto_20201214_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='prosfora',
            name='document',
            field=models.FileField(default='-', upload_to='documents'),
        ),
    ]
