# Generated by Django 3.0.7 on 2020-11-19 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timologisi', '0004_auto_20201107_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='prosfora',
            name='prosfora_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ημ.Αποστολής Προσφ.'),
            preserve_default=False,
        ),
    ]
