# Generated by Django 3.0.7 on 2020-11-23 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timologisi', '0005_prosfora_prosfora_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='ammount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='prosfora',
            name='prosfora_date',
        ),
    ]
