# Generated by Django 3.0.7 on 2020-12-26 15:39

from django.db import migrations, models
import timologisi.models


class Migration(migrations.Migration):

    dependencies = [
        ('timologisi', '0005_prosfora_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosfora',
            name='document',
            field=models.FileField(default='-', upload_to=timologisi.models.Prosfora.user_directory_path),
        ),
    ]
