# Generated by Django 3.0.7 on 2020-12-05 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timologisi', '0006_auto_20201123_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='contract_ammount',
            new_name='poso',
        ),
    ]
