# Generated by Django 3.0.7 on 2020-12-26 16:59

from django.db import migrations, models
import timologisi.models


class Migration(migrations.Migration):

    dependencies = [
        ('timologisi', '0006_auto_20201226_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='file',
            field=models.FileField(default='-', upload_to=timologisi.models.Contract.user_directory_path),
        ),
    ]
