# Generated by Django 3.0.7 on 2020-12-26 19:16

from django.db import migrations, models
import timologisi.models


class Migration(migrations.Migration):

    dependencies = [
        ('timologisi', '0007_contract_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='file',
            field=models.FileField(blank=True, default='-', null=True, upload_to=timologisi.models.Contract.user_directory_path),
        ),
        migrations.AlterField(
            model_name='prosfora',
            name='document',
            field=models.FileField(blank=True, default='-', null=True, upload_to=timologisi.models.Prosfora.user_directory_path),
        ),
    ]
