# Generated by Django 3.0.7 on 2020-12-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timologisi', '0007_auto_20201205_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosfora',
            name='poso',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
