# Generated by Django 3.0.7 on 2021-01-02 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timologisi', '0008_auto_20201226_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='amount',
            new_name='poso',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Ημ.Πληρωμ.'),
        ),
    ]
