# Generated by Django 3.0.7 on 2021-01-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timologisi', '0009_auto_20210102_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='contract_code',
            field=models.CharField(choices=[('HARD00', 'HARD00'), ('SOFT00', 'SOFT00')], max_length=150, verbose_name='Κωδικός Σύμβ.'),
        ),
    ]
