# Generated by Django 3.0.7 on 2021-01-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timologisi', '0010_auto_20210102_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
    ]
