# Generated by Django 3.0.7 on 2021-01-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timologisi', '0012_auto_20210112_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
