# Generated by Django 3.0.7 on 2021-01-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timologisi', '0013_auto_20210113_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
    ]
