# Generated by Django 3.0.7 on 2021-01-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timologisi', '0014_auto_20210113_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
