# Generated by Django 3.0.7 on 2021-01-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timologisi', '0016_prosfora_tax_poso'),
    ]

    operations = [
        migrations.AddField(
            model_name='prosfora',
            name='is_ongoing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_code',
            field=models.CharField(choices=[('HARD00', 'HARD00'), ('SOFT00', 'SOFT00'), ('SERV00', 'SERV00')], max_length=150, verbose_name='Κωδικός Σύμβ.'),
        ),
    ]
